"""Writing a corpus whose answers are known, because they were written first.

Phase 10 grades extractions against this. Phase 3 uses it as test data, which
is the reason it is built now rather than then: the pipeline needs documents
with decisions, assumptions, estimates and outcomes actually in them, and
inventing those twice would produce two corpora that disagree.

Three properties, each tested:

- **Deterministic.** Same seed, same bytes -- including the answer key and the
  timestamps inside the documents, which are measured from a fixed epoch rather
  than from today. A corpus that changed overnight would move every metric
  recorded against it for a reason that is not a change.
- **Self-verifying.** `generate_corpus` runs `verify_corpus` over what it just
  wrote and refuses to return a corpus with a problem in it. A generator bug
  produces an answer key that is wrong in a way no downstream test can detect
  on its own, so the check belongs here, at the moment the mistake is cheap.
- **Written in the reader's coordinates.** Offsets go into the *normalised
  content* an adapter produces, which for a JSON source is not the file at all.

Topics repeat across templates on purpose, so one subject appears as an ADR, as
the meeting it came out of, and as the status update that closed it. That is
what a real corpus looks like, and it is what makes contradiction and
archaeology gradeable in the phases that build them.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from random import Random
from typing import Final

from praxis.corpus.drafting import Draft, Ids
from praxis.corpus.groundtruth import (
    DOCUMENTS_DIRNAME,
    CorpusGroundTruth,
    DocumentGroundTruth,
    content_hash,
    verify_corpus,
    write_ground_truth,
)
from praxis.corpus.templates import TEMPLATES, Written, revision_note, world_assumption_key
from praxis.corpus.topics import TOPICS, Topic
from praxis.obs.logging import get_logger

_log = get_logger(__name__)

GENERATOR_VERSION: Final = 2
"""Bumped whenever generated text changes. Recorded in the answer key, so a
corpus generated by an older build is recognisable rather than merely
different."""

DEFAULT_DOCUMENTS: Final = 12
"""Enough that every template appears at least three times and four topics
appear in two document kinds. Small enough that the whole corpus is ingested in
a test without anyone thinking about it."""

DEFAULT_REVISIONS: Final = 4
"""Revision notes written after the main pass, each overturning one assumption.

A second pass rather than a fifth template, because a revision is a *reply* to
a document that already exists: scheduling it in the rotation would let one be
written before the assumption it revises, and its `contradicts` edge would have
nothing to point at. Four rather than eight so that the corpus contains
assumptions which are overturned and assumptions which are not -- a detector
that flagged every pair would otherwise score perfectly.
"""


class CorpusError(Exception):
    """Raised when a generated corpus does not survive its own verification."""


@dataclass(frozen=True, slots=True)
class _Plan:
    """Which topic gets written in which shape, for one document."""

    index: int
    topic_index: int
    template_index: int


def generate_corpus(
    root: Path,
    *,
    documents: int = DEFAULT_DOCUMENTS,
    revisions: int = DEFAULT_REVISIONS,
    seed: int,
    generated_at: datetime,
) -> CorpusGroundTruth:
    """Write a corpus and its answer key, and prove the key still fits.

    Args:
        root: Directory to write into. Created if missing; existing documents
            with the same names are overwritten, which is what regenerating
            means.
        documents: How many to write in the main pass.
        revisions: How many revision notes to write after it, each overturning
            an assumption an earlier document stated. Zero writes none, which
            is what a caller wanting only the Phase 3 corpus asks for.
        seed: Seeds every choice the templates make. Two runs with one seed
            produce byte-identical output.
        generated_at: Recorded in the key. Timezone-aware, invariant 5.

    Returns:
        The answer key, as written.

    Raises:
        ValueError: if asked for no documents, or for a naive timestamp.
        CorpusError: if the corpus does not verify against itself. A generator
            bug produces a key that is wrong in a way nothing downstream can
            detect, so it fails here rather than being written out.
    """
    if documents < 1:
        message = f"a corpus needs at least one document, got {documents}"
        raise ValueError(message)
    if revisions < 0:
        message = f"a corpus cannot have {revisions} revision notes"
        raise ValueError(message)
    if generated_at.tzinfo is None:
        message = "generated_at must be timezone-aware"
        raise ValueError(message)

    (root / DOCUMENTS_DIRNAME).mkdir(parents=True, exist_ok=True)
    ids = Ids()
    recorded: dict[str, str] = {}
    rng = Random(seed)  # noqa: S311 -- reproducibility, not secrecy
    written = [_write(root, _draft(plan, ids, recorded, rng)) for plan in _schedule(documents)]
    written += [
        _write(root, _revision(topic, index, ids, recorded, rng))
        for index, topic in enumerate(_revisable(recorded)[:revisions], start=documents)
    ]

    truth = CorpusGroundTruth(
        generator_version=GENERATOR_VERSION,
        seed=seed,
        generated_at=generated_at,
        documents=tuple(written),
    )
    write_ground_truth(root, truth)

    problems = verify_corpus(root)
    if problems:
        listed = "\n  - ".join(problems)
        message = f"the generated corpus does not verify against itself:\n  - {listed}"
        raise CorpusError(message)

    _log.info(
        "corpus_generated",
        root=str(root),
        documents=len(truth.documents),
        items=len(truth.items),
        seed=seed,
    )
    return truth


def _schedule(documents: int) -> tuple[_Plan, ...]:
    """Decide which topic is written in which shape, for every document.

    The template advances with the index *and* with how many times the topic
    list has been round, so the second pass over a topic writes it in a
    different shape. Straight modular arithmetic would give each topic the same
    template forever, and the corpus would never contain one subject seen two
    ways -- which is exactly what later phases have to reason across.
    """
    return tuple(
        _Plan(
            index=index,
            topic_index=index % len(TOPICS),
            template_index=(index + index // len(TOPICS)) % len(TEMPLATES),
        )
        for index in range(documents)
    )


def _draft(plan: _Plan, ids: Ids, recorded: dict[str, str], rng: Random) -> Written:
    """Run one template over one topic.

    The registry is passed by reference and shared across every draft, which is
    how a revision note in the second pass finds the assumption it overturns.
    """
    template = TEMPLATES[plan.template_index]
    return template(TOPICS[plan.topic_index], Draft(ids=ids, recorded=recorded), rng, plan.index)


def _revisable(recorded: dict[str, str]) -> tuple[Topic, ...]:
    """The topics whose world assumption some document actually stated.

    Only two of the four templates record one -- a status update and an issue
    export state an estimate and a decision but no assumption -- so revising a
    topic in topic order would write notes overturning assumptions that were
    never written down, and their `contradicts` edges would point at nothing.

    Taken in `TOPICS` order rather than sampled, so which assumptions get
    overturned is a function of `revisions` alone and the corpus keeps a stable
    mix of assumptions that were revised and assumptions that were not.
    """
    return tuple(topic for topic in TOPICS if world_assumption_key(topic) in recorded)


def _revision(topic: Topic, index: int, ids: Ids, recorded: dict[str, str], rng: Random) -> Written:
    """Write one revision note, overturning an assumption already in the corpus."""
    return revision_note(topic, Draft(ids=ids, recorded=recorded), rng, index)


def _write(root: Path, written: Written) -> DocumentGroundTruth:
    """Put one document on disk and describe it in the key.

    The hash and length are of the *content* an adapter will produce, never of
    the file, because that is the only thing a span's offsets are measured
    against. Items are sorted into document order, which is not the order they
    were recorded in -- a template records an estimate before the assumption
    that links to it, because the link names an id that has to exist.
    """
    relative = f"{DOCUMENTS_DIRNAME}/{written.filename}"
    (root / relative).write_bytes(written.file_bytes)
    raw = written.content.encode("utf-8")
    return DocumentGroundTruth(
        path=relative,
        source_kind=written.source_kind,
        content_sha256=content_hash(raw),
        byte_length=len(raw),
        items=tuple(sorted(written.items, key=lambda item: item.start_byte)),
    )
