"""Writing a corpus whose answers are known, because they were written first.

Phase 10 grades extractions against this. Phase 3 uses it as test data, which
is the reason it is built now rather than then: the pipeline needs documents
with decisions, assumptions, estimates and outcomes actually in them, and
inventing those twice would produce two corpora that disagree.

Three properties, each tested:

- **Deterministic.** Same seed, same bytes -- including the answer key and the
  timestamps inside the documents, which are measured from a fixed epoch rather
  than from today. A corpus that changed overnight would move every metric
  recorded against it for a reason that is not a change.
- **Self-verifying.** `generate_corpus` runs `verify_corpus` over what it just
  wrote and refuses to return a corpus with a problem in it. A generator bug
  produces an answer key that is wrong in a way no downstream test can detect
  on its own, so the check belongs here, at the moment the mistake is cheap.
- **Written in the reader's coordinates.** Offsets go into the *normalised
  content* an adapter produces, which for a JSON source is not the file at all.

Topics repeat across templates on purpose, so one subject appears as an ADR, as
the meeting it came out of, and as the status update that closed it. That is
what a real corpus looks like, and it is what makes contradiction and
archaeology gradeable in the phases that build them.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from random import Random
from typing import Final

from praxis.corpus.controls import adversarial_memo, clean_control, orphan_note
from praxis.corpus.drafting import Draft, Ids
from praxis.corpus.groundtruth import (
    DOCUMENTS_DIRNAME,
    CorpusGroundTruth,
    DocumentGroundTruth,
    ExpectedVerdict,
    GroundTruthItem,
    ItemKind,
    MonitoringExpectation,
    content_hash,
    verify_corpus,
    write_ground_truth,
)
from praxis.corpus.measurements import satisfying, violating
from praxis.corpus.templates import TEMPLATES, Written, revision_note, world_assumption_key
from praxis.corpus.topics import TOPICS, Topic
from praxis.domain.enums import AssumptionStatus
from praxis.domain.links import LinkType
from praxis.obs.logging import get_logger
from praxis.predicates.errors import PredicateSyntaxError
from praxis.predicates.evaluator import evaluate
from praxis.predicates.parser import parse
from praxis.predicates.world import WorldState

_log = get_logger(__name__)

GENERATOR_VERSION: Final = 4
"""Bumped whenever generated text changes. Recorded in the answer key, so a
corpus generated by an older build is recognisable rather than merely
different."""

DEFAULT_DOCUMENTS: Final = 60
"""Sixteen topics across four templates, so no shape is written twice.

Was 12 through Phase 9. Sixty is the corpus size the original brief named and
what the ablation table needs to say anything.
"""

DEFAULT_REVISIONS: Final = 8
"""Revision notes written after the main pass, each overturning one assumption.

A second pass rather than a fifth template, because a revision is a *reply* to
a document that already exists: scheduling it in the rotation would let one be
written before the assumption it revises, and its `contradicts` edge would have
nothing to point at. Fewer than the revisable topics, so the corpus contains
assumptions which are overturned and assumptions which are not -- a detector
that flagged every pair would otherwise score perfectly.
"""

DEFAULT_CONTROLS: Final = 6
"""Operational documents with no answers in them at all. Anything extracted
from one is a false positive by construction."""

DEFAULT_ADVERSARIAL: Final = 4
"""Memos in which every extractable-looking sentence is a labelled negative."""

DEFAULT_ORPHANS: Final = 4
"""Notes stating an assumption no decision rests on -- retirement candidates."""

_Template = Callable[[Topic, Draft, Random, int], Written]
"""What every template in this package is, control ones included."""


class CorpusError(Exception):
    """Raised when a generated corpus does not survive its own verification."""


@dataclass(frozen=True, slots=True)
class _Plan:
    """Which topic gets written in which shape, for one document."""

    index: int
    topic_index: int
    template_index: int


@dataclass(frozen=True, slots=True)
class Controls:
    """How many of each kind of control document to write after the main pass.

    One object rather than three parameters so `generate_corpus` keeps a
    signature a person can read.

    Attributes:
        clean: Operational documents with nothing to extract.
        adversarial: Memos whose every extractable-looking sentence is labelled
            as one that must not be extracted.
        orphans: Notes stating an assumption no decision rests on.
    """

    clean: int = DEFAULT_CONTROLS
    adversarial: int = DEFAULT_ADVERSARIAL
    orphans: int = DEFAULT_ORPHANS

    def total(self) -> int:
        """How many documents these three passes write between them."""
        return self.clean + self.adversarial + self.orphans

    def passes(self) -> tuple[tuple[_Template, int], ...]:
        """Each control template with the number of documents it writes."""
        return (
            (clean_control, self.clean),
            (adversarial_memo, self.adversarial),
            (orphan_note, self.orphans),
        )


DEFAULT_CONTROL_MIX: Final = Controls()
"""The mix `generate_corpus` writes when a caller says nothing."""


def generate_corpus(  # noqa: PLR0913 -- one argument per pass, plus seed and clock
    root: Path,
    *,
    documents: int = DEFAULT_DOCUMENTS,
    revisions: int = DEFAULT_REVISIONS,
    controls: Controls = DEFAULT_CONTROL_MIX,
    seed: int,
    generated_at: datetime,
) -> CorpusGroundTruth:
    """Write a corpus and its answer key, and prove the key still fits.

    Args:
        root: Directory to write into. Created if missing; existing documents
            with the same names are overwritten, which is what regenerating
            means.
        documents: How many to write in the main pass.
        revisions: How many revision notes to write after it, each overturning
            an assumption an earlier document stated. Zero writes none, which
            is what a caller wanting only the Phase 3 corpus asks for.
        controls: How many of each kind of control document to write last.
            `Controls(0, 0, 0)` writes the Phase 3 to 9 corpus and nothing else.
        seed: Seeds every choice the templates make. Two runs with one seed
            produce byte-identical output.
        generated_at: Recorded in the key. Timezone-aware, invariant 5.

    Returns:
        The answer key, as written.

    Raises:
        ValueError: if asked for no documents, for a negative count, or for a
            naive timestamp.
        CorpusError: if the corpus does not verify against itself. A generator
            bug produces a key that is wrong in a way nothing downstream can
            detect, so it fails here rather than being written out.
    """
    if documents < 1:
        message = f"a corpus needs at least one document, got {documents}"
        raise ValueError(message)
    if revisions < 0:
        message = f"a corpus cannot have {revisions} revision notes"
        raise ValueError(message)
    if min(controls.clean, controls.adversarial, controls.orphans) < 0:
        message = f"a corpus cannot have a negative number of controls: {controls}"
        raise ValueError(message)
    if generated_at.tzinfo is None:
        message = "generated_at must be timezone-aware"
        raise ValueError(message)

    (root / DOCUMENTS_DIRNAME).mkdir(parents=True, exist_ok=True)
    ids = Ids()
    recorded: dict[str, str] = {}
    rng = Random(seed)  # noqa: S311 -- reproducibility, not secrecy
    written = [_write(root, _draft(plan, ids, recorded, rng)) for plan in _schedule(documents)]
    written += [
        _write(root, _revision(topic, index, ids, recorded, rng))
        for index, topic in enumerate(_revisable(recorded)[:revisions], start=documents)
    ]
    # Last, so a control's index never collides with a real document's and the
    # file names still sort into the order they were written.
    for template, count in controls.passes():
        written += [
            _write(root, _control(template, index, ids, recorded, rng))
            for index in range(len(written), len(written) + count)
        ]

    documented = tuple(written)
    truth = CorpusGroundTruth(
        generator_version=GENERATOR_VERSION,
        seed=seed,
        generated_at=generated_at,
        documents=documented,
        monitoring=_monitoring(documented, generated_at),
    )
    write_ground_truth(root, truth)

    problems = verify_corpus(root)
    if problems:
        listed = "\n  - ".join(problems)
        message = f"the generated corpus does not verify against itself:\n  - {listed}"
        raise CorpusError(message)

    _log.info(
        "corpus_generated",
        root=str(root),
        documents=len(truth.documents),
        items=len(truth.items),
        seed=seed,
    )
    return truth


def _schedule(documents: int) -> tuple[_Plan, ...]:
    """Decide which topic is written in which shape, for every document.

    The template advances with the index *and* with how many times the topic
    list has been round, so the second pass over a topic writes it in a
    different shape. Straight modular arithmetic would give each topic the same
    template forever, and the corpus would never contain one subject seen two
    ways -- which is exactly what later phases have to reason across.
    """
    return tuple(
        _Plan(
            index=index,
            topic_index=index % len(TOPICS),
            template_index=(index + index // len(TOPICS)) % len(TEMPLATES),
        )
        for index in range(documents)
    )


def _draft(plan: _Plan, ids: Ids, recorded: dict[str, str], rng: Random) -> Written:
    """Run one template over one topic.

    The registry is passed by reference and shared across every draft, which is
    how a revision note in the second pass finds the assumption it overturns.
    """
    template = TEMPLATES[plan.template_index]
    return template(TOPICS[plan.topic_index], Draft(ids=ids, recorded=recorded), rng, plan.index)


def _revisable(recorded: dict[str, str]) -> tuple[Topic, ...]:
    """The topics whose world assumption some document actually stated.

    Only two of the four templates record one -- a status update and an issue
    export state an estimate and a decision but no assumption -- so revising a
    topic in topic order would write notes overturning assumptions that were
    never written down, and their `contradicts` edges would point at nothing.

    Taken in `TOPICS` order rather than sampled, so which assumptions get
    overturned is a function of `revisions` alone and the corpus keeps a stable
    mix of assumptions that were revised and assumptions that were not.
    """
    return tuple(topic for topic in TOPICS if world_assumption_key(topic) in recorded)


def _revision(topic: Topic, index: int, ids: Ids, recorded: dict[str, str], rng: Random) -> Written:
    """Write one revision note, overturning an assumption already in the corpus."""
    return revision_note(topic, Draft(ids=ids, recorded=recorded), rng, index)


def _control(
    template: _Template, index: int, ids: Ids, recorded: dict[str, str], rng: Random
) -> Written:
    """Write one control document, rotating topics the way the main pass does.

    A control carries a topic so it reads like the rest of the corpus. A
    document an extractor could skip on its shape would test nothing.
    """
    return template(TOPICS[index % len(TOPICS)], Draft(ids=ids, recorded=recorded), rng, index)


def _write(root: Path, written: Written) -> DocumentGroundTruth:
    """Put one document on disk and describe it in the key.

    The hash and length are of the *content* an adapter will produce, never of
    the file, because that is the only thing a span's offsets are measured
    against. Items are sorted into document order, which is not the order they
    were recorded in -- a template records an estimate before the assumption
    that links to it, because the link names an id that has to exist.
    """
    relative = f"{DOCUMENTS_DIRNAME}/{written.filename}"
    (root / relative).write_bytes(written.file_bytes)
    raw = written.content.encode("utf-8")
    return DocumentGroundTruth(
        path=relative,
        source_kind=written.source_kind,
        content_sha256=content_hash(raw),
        byte_length=len(raw),
        items=tuple(sorted(written.items, key=lambda item: item.start_byte)),
    )


def _monitoring(
    documents: tuple[DocumentGroundTruth, ...], generated_at: datetime
) -> MonitoringExpectation:
    """The world a monitoring run is graded in, and what should follow from it.

    Two steps, and the order is the correctness argument.

    **First the world is chosen, then every verdict is computed from it.** The
    obvious construction is to give each assumption a role and add whichever
    measurement that role needs, and it is wrong: two documents in this corpus
    state `index_size_gb <= 50`, so a key asserting one of them holding and the
    other breached would write one fact twice and be wrong about one of them --
    silently, and in a way that would surface as a monitor bug. Deriving the
    verdicts from the assembled world instead makes that unrepresentable.

    The world is chosen to make the distinction this phase is graded on
    measurable. An assumption a revision note overturned is measured at a value
    its own predicate forbids; every second one of the rest is measured at a
    value its predicate permits; the others are not measured at all. A corpus
    where everything was breached would let a monitor that always cries breach
    score perfectly, and one where nothing was would let a monitor that never
    does.

    **What this grades is the pipeline, not the arithmetic.** The verdicts come
    from the same evaluator the monitor uses, so the corpus cannot catch an
    evaluator bug -- `tests/predicates/` is what does that. What it does catch
    is everything between a document and a status: extraction, formalization,
    whether the predicate that got stored still means what the document said,
    and whether the monitor wrote the verdict it reached.
    """
    items = [item for document in documents for item in document.items]
    facts = _world_facts(items)
    world = WorldState(now=generated_at, facts=_as_decimals(facts))
    return MonitoringExpectation(
        facts=facts,
        events=(),
        as_of=generated_at,
        verdicts=tuple(_verdict_for(item, world) for item in _graded(items)),
    )


def _graded(items: list[GroundTruthItem]) -> list[GroundTruthItem]:
    """The assumptions a monitoring expectation is written for.

    The reversal a revision note states is left out. Its subject is the one
    quantity that was measured -- to breach the original -- so it would come out
    holding, and asserting that would be the corpus grading its own arithmetic
    rather than the monitor.
    """
    reversals = {
        item.item_id
        for item in items
        for link in item.links
        if link.link_type is LinkType.CONTRADICTS
    }
    return [
        item
        for item in items
        if item.kind is ItemKind.ASSUMPTION
        and not item.is_distractor
        and item.item_id not in reversals
    ]


def _world_facts(items: list[GroundTruthItem]) -> dict[str, str]:
    """The measurements a monitoring run is given.

    Breaching measurements are placed first, so an assumption an earlier
    document also stated is breached too rather than fighting over one fact.
    """
    overturned = {
        link.target_item_id
        for item in items
        for link in item.links
        if link.link_type is LinkType.CONTRADICTS
    }
    graded = _graded(items)
    facts: dict[str, str] = {}
    for item in graded:
        if item.item_id in overturned:
            _measure(facts, item, violating)
    # Every second remaining assumption, by position rather than by anything
    # derived from the id: `hash` on a string varies with PYTHONHASHSEED, and a
    # corpus whose answer key changed between processes would have lost the one
    # property it may never lose.
    for position, item in enumerate(graded):
        if item.item_id not in overturned and position % 2 == 0:
            _measure(facts, item, satisfying)
    return facts


def _measure(
    facts: dict[str, str],
    item: GroundTruthItem,
    witness: Callable[[str], tuple[str, Decimal] | None],
) -> None:
    """Add one measurement, leaving a quantity already measured alone."""
    found = witness(_expected_field(item, "predicate"))
    if found is not None and found[0] not in facts:
        facts[found[0]] = str(found[1])


def _verdict_for(item: GroundTruthItem, world: WorldState) -> ExpectedVerdict:
    """What follows from the world for one assumption.

    `UNVERIFIED` is a real expectation and the most common one: most assumptions
    in any corpus have never been measured, and a monitor that reached a verdict
    about those would be guessing -- which is the failure this phase is arranged
    to prevent.
    """
    predicate = _expected_field(item, "predicate")
    try:
        evaluation = evaluate(parse(predicate), world)
    except PredicateSyntaxError:  # pragma: no cover -- every generated predicate parses
        return ExpectedVerdict(
            item_id=item.item_id,
            status=AssumptionStatus.UNVERIFIED,
            note="its predicate does not parse, so nothing can evaluate it",
        )
    if evaluation.violated:
        return ExpectedVerdict(
            item_id=item.item_id,
            status=AssumptionStatus.BREACHED,
            note=f"`{predicate}` is false against the measurements this corpus supplies",
        )
    if evaluation.holds:
        return ExpectedVerdict(
            item_id=item.item_id,
            status=AssumptionStatus.HOLDING,
            note=f"`{predicate}` is true against the measurements this corpus supplies",
        )
    return ExpectedVerdict(
        item_id=item.item_id,
        status=AssumptionStatus.UNVERIFIED,
        note=f"nothing measures `{predicate}`, so no verdict is available",
    )


def _as_decimals(facts: dict[str, str]) -> dict[str, Decimal]:
    """The facts as the evaluator reads them. Never float -- invariant 4."""
    return {name: Decimal(value) for name, value in facts.items()}


def _expected_field(item: GroundTruthItem, name: str) -> str:
    """One expected field's value, or empty when the item does not carry it."""
    return next((field.value for field in item.fields if field.name == name), "")
